### PR TITLE
Remove explicit Docker container names to allow storing multiple in parallel.

### PR DESCRIPTION
**Pull request by zorbathut**

### CODE REVIEW

**Comment by official-techsupport** [comment]
The failed test tells you to replace `result.trim()` with ` result.strip()`

**Comment by justcool393** [comment]
i've done this more times than i can count

**Comment by zorbathut** [comment]
siiiigh

**Comment by zorbathut** [comment]
Yeah I was actually expecting that to fail this time.

I'll figure out what's wrong.

**Comment by official-techsupport** [comment]
@zorbathut you have now got rid of both the `--wait` flags and of manual waiting for containers to start/stop/fail. Is that intentional?

**Comment by zorbathut** [comment]
> @zorbathut you have now got rid of both the `--wait` flags and of manual waiting for containers to start/stop/fail. Is that intentional?

Actually I should probably document this :V

The problem with `--wait` is that it waits for the containers to be healthy, but it doesn't have any escape for if the containers will never be healthy. If you break a container, it'll just sit there, forever, waiting. This is not useful.

The problem with trying to get container status is that it's annoyingly hard to actually get a list of valid containers unless you know their name. There's a feature on newer versions of Docker, but not on anything Github Actions supports with an LTS Ubuntu distro.

This *seems* to work, and I admit it seems sketchy, but by default `docker-compose up` appears to wait for the first attempt at starting them - that is, it exits once all containers have made a shot at starting. Then, either the container works, or it doesn't. If it works we don't need to test, if it doesn't, the execute will fail anyway.

Gonna add a comment to this.

**Review by official-techsupport — APPROVED** [review]

**Pull request merged**
