### PR TITLE
remove holes

### PR DESCRIPTION
**Pull request by justcool393**
would remove holes. (ref #470)

### CODE REVIEW

**Comment by zorbathut** [comment]
Seems reasonable to me; right now most of the effort for the foreseeable future is just working on the existing community, and I think we'd need some pretty big code changes before I felt comfortable splitting off into multiple communities anyway.

(also whoops just realized this was waiting for a reply)

**Comment by justcool393** [comment]
blocking on #536 (migration)

**Comment by zorbathut** [comment]
#536 is in!

**Review by TLSM — APPROVED** [review]
Did a once-over for any missed references to the subs ("holes") system or its tendrils in the classes and removed them pre-review. Manually performed basic E2E testing on posting and commenting and viewing posts, comment contexts, and userpages (each route endpoint affected by PR). Migration worked locally.

**Pull request merged**
