### PR TITLE
combine postToast variants

### LINKED ISSUE #576: frontend: combine postToast variants
see: https://github.com/themotte/rDrama/pull/434#issuecomment-1334700671

### PR DESCRIPTION
**Pull request by justcool393**
fixes #576

### CODE REVIEW

**Comment by justcool393** [comment]
okay checked for some errors

**Comment by justcool393** [comment]
note: if #652 is merged before, need to fix using old system

**Comment by zorbathut** [comment]
Whoops, merged in #652 before seeing this. Sorry 'bout that. Ping me once it's updated, I'll review it.

**Comment by justcool393** [comment]
okay new JS should be integrated properly. tested it out and it seems to work

**Review by zorbathut — APPROVED** [review]

**Pull request merged**
