### PR TITLE
[#39] Add migrations using alembic

### PR DESCRIPTION
**Pull request by faul-sname**
Add revisions to the project.

Usage
```sh
# Run migrations for the first time (will automatically create the `alembic_version` table
$ flask db upgrade
# Run all forward migrations
$ flask db upgrade
# Run one reverse migration
$ flask db downgrade
# Autogenerate a revision file from the current schema:
$ flask db revision --autogenerate --message='a short message describing what you changed'
```

**Things to Note When Creating a Revision:**
1. The above commands should be run from within the `files` container -- the equivalent command from outside the container is
```sh
docker-compose exec -T files bash -c 'cd /service; FLASK_APP="files/cli:app" flask db upgrade''
```
I have a bash function which is a shortcut for the above:
```sh
function motteflask {
	docker-compose exec -T files bash -c 'cd /service/; FLASK_APP="files/cli:app" flask "$@"' . "$@"
}
```
If you throw a similar function in your `~/.bashrc` or similar, you would do
```sh
$ motteflask db upgrade
```
2. If there are foreign key constraints (or any other constraints) added by your revision, make sure that the constraints are named -- your downgrade migrations will fail if the constraints are not named.

**Bad:**  
```python
def upgrade():
        op.create_foreign_key(None, 'comments', 'oauth_apps', ['app_id'], ['id'])
```
**Good:**
```python
def upgrade():
    op.create_foreign_key('comments_app_id_fkey', 'comments', 'oauth_apps', ['app_id'], ['id'])
```

### CODE REVIEW

**Comment by faul-sname** [comment]
As of the commit where I'm leaving this comment, running `flask db revision --autogenerate` creates an empty revision, and the only changes from running the below sequence of commands is to add the `alembic_version` table.
```sh
flask db init
flask db revision --autogenerate
flask db upgrade
$ diff <(cat schema.sql | grep '\S') <(
    docker-compose exec -T postgres pg_dump -U postgres postgres --schema-only \
        | sed 's/Owner: \(postgres\|$\)/Owner: -/g' \
        | grep -v 'ALTER .* OWNER TO postgres' \
        | grep '\S'
    )
4,5c4,5
< -- Dumped from database version 13.6
< -- Dumped by pg_dump version 14.2 (Ubuntu 14.2-1.pgdg20.04+1)
---
> -- Dumped from database version 12.3 (Debian 12.3-1.pgdg100+1)
> -- Dumped by pg_dump version 12.3 (Debian 12.3-1.pgdg100+1)
92a93,98
> -- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
> --
> CREATE TABLE public.alembic_version (
>     version_num character varying(32) NOT NULL
> );
> --
559a566,570
> -- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
> --
> ALTER TABLE ONLY public.alembic_version
>     ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);
> --
1238a1250,1252
> --
> -- PostgreSQL database dump complete
> --
```

**Comment by zorbathut** [comment]
Oh man, this is great :D

Inevitably I'm running into some trouble to start with. `flask db` gives the error `No such command "db".` I'm pretty sure I just don't have the flask module installed. Back to this in a sec!

I'm also a little unsure of how this ends up connecting to the db; I'm assuming the db server needs to be running at the time? Does the flask stuff need to run *inside* the docker environment, or can it run outside the docker environment but with `flask db` installed?

Also, if you do end up with updates, are they autoapplied on startup or do they have to be done manually?

I'm tempted to make a little flask-db wrapper that parallels how `run_tests.py` works, which basically starts up the environment and then execs stuff inside `themotte` container. I'm also tempted to rig up the container to automatically update if any updates are pending. Let me know if these make sense!

I'm pretty sure this is quite close to being done, there's just a little bit of polish left to get it integrated into the environment cleanly. Many thanks in advance!

**Comment by faul-sname** [comment]
> Inevitably I'm running into some trouble to start with. flask db gives the error No such command "db". I'm pretty sure I just don't have the flask module installed. Back to this in a sec!

You need to run the commands within the `files` container, e.g.
```sh
docker-compose exec -T files sh -c 'cd /service; FLASK_APP=files/env:app flask db current
```

I find it helpful to have a bash function in my `~/.bashrc` (well technically in a file that get sourced in my `~/.bashrc) with

```sh
function motteflask {
	docker-compose exec -T files bash -c 'cd /service/; FLASK_APP="files/cli:app" flask "$@"' . "$@"
}
```
at which point the command is
```sh
$ motteflask db upgrade
```

> I'm also a little unsure of how this ends up connecting to the db; I'm assuming the db server needs to be running at the time? Does the flask stuff need to run inside the docker environment, or can it run outside the docker environment but with flask db installed?

This needs the DB to be running in order to work. Since the `files` container depends on the `postgres` container, if you run this from within the `files` container, the db is guaranteed to be running.

> Also, if you do end up with updates, are they autoapplied on startup or do they have to be done manually?

Migrations are autoapplied on container startup. However, if you do a `git pull` and do not restart your container, you will need to run a `flask db upgrade` to ensure your DB is up to date.

> I'm tempted to make a little flask-db wrapper that parallels how run_tests.py works, which basically starts up the environment and then execs stuff inside themotte container. I'm also tempted to rig up the container to automatically update if any updates are pending. Let me know if these make sense!

If you mean "I'm tempted to rig up the container to immediately run all migrations whenever there are any changes in the `migrations/versions` directory, I'd prefer not to do that since autogenerated migrations are not necessarily final (e.g. you might notice that your column is of the wrong type and want to wipe the migration and try again, or notice that your fk constraint has no name and you need to name it).

If you mean "add a git pre-merge-commit hook that runs migrations", so that migrations are automatically applied when people do a `git fetch origin; git merge origin/frost`, go for it.

> I'm pretty sure this is quite close to being done, there's just a little bit of polish left to get it integrated into the environment cleanly. Many thanks in advance!

Let me know if there's anything else

**Comment by faul-sname** [comment]
Also as a note, there's now a test to ensure that migrations are up to date. Once this PR is merged in, tests will fail if the DB is not up to date.

**Review by zorbathut — APPROVED** [review]

**Pull request merged**
