### PR TITLE
Make commenting the default

### LINKED ISSUE #314: Default view on a user's page should be comments, not posts

### LINKED ISSUE #609: Swap posts and comments on profile pages, default to comments.

### PR DESCRIPTION
**Pull request by justcool393**
fixes #314 and fixes #609

### CODE REVIEW

**Comment by justcool393** [comment]
note hasn't been tested yet and I still need to do another pass on this. having some issues with some migrations making alembic unhappy so it may be a slight bit

**Comment by justcool393** [comment]
still has some issues with saved comments/posts

**Comment by justcool393** [comment]
ready for review

**Comment by zorbathut** [comment]
Request: Instead of changing `userpage` and `userpage_comments` into `userpage_submissions` and `userpage`, just switch 'em to `userpage_submissions` and `userpage_comments`. I don't think there's a good reason to promote one of those to being the base type, let's just have two variants.

(also it makes the diff kinda nightmarish)

Rest of it looks good! This was a boring and timeconsuming change, many thanks for doing it :)

**Review by zorbathut — APPROVED** [review]

**Comment by zorbathut** [comment]
Oh, nice, that's even cleaner than I was thinking.

Just waiting for unit tests and I'll check it in :)

**Review by zorbathut — APPROVED** [review]

**Pull request merged**
