### PR TITLE
Fix notifications from blocked users

### PR DESCRIPTION
**Pull request by wmill**
Fix for #640 

New notifications from blocked users were already blocked. This is for rendering of older notifications after the block happened.

### CODE REVIEW

**Comment by zorbathut** [comment]
That is a gnarly comments.html diff. I recognize most of it comes from correcting a whitespace error but it's kinda unreadable. Can you do one of:

* Undo the whitespace fix, with my acknowledgement that it's wrong and should be fixed later
* Send another pull request *just* with the whitespace fix and I'll get that one merged in first
* Say "sorry, I don't have time for that right now, I apologize" and I'll go do it myself in a day or two :V

**Comment by wmill** [comment]
I'll do it

**Comment by wmill** [comment]
The comments.html change just displayed the block user status like in comments. Without it the notification just doesn't render so there's no real point to bothering with it.

**Comment by zorbathut** [comment]
Looks good! Many thanks, I'll go get this updated :D

**Review by zorbathut — APPROVED** [review]

**Pull request merged**
