### PR TITLE
Refactor auth forms

### PR DESCRIPTION
**Pull request by justcool393**
These forms are pretty terrible in every way, we copy and paste the markup multiple times for some unheard of reason. This kinda fixes that.

### CODE REVIEW

**Review by TLSM — CHANGES_REQUESTED** [review]
- `login/login.html` doesn't extend authforms
- `login/sign_up.html` doesn't extend authforms
- `login/reset_password.html` doesn't exist: it's still `reset_password.html`, which needs to be moved into the "login" directory to match the others, and needs to extend the new authforms path. Also fix the indentation while moving it?

For testing the actual change, `GET /forgot` (login/forgot_password.html) is the easiest one to test the new authforms work on. It looks pretty good, but the vertical alignment of the form is off-center, and there's a white rectangle (ostensibly a navbar) at the top of the page.

**Comment by justcool393** [comment]
> * `login/login.html` doesn't extend authforms
> 
>     * `login/sign_up.html` doesn't extend authforms
> 
>     * `login/reset_password.html` doesn't exist: it's still `reset_password.html`, which needs to be moved into the "login" directory to match the others, and needs to extend the new authforms path. Also fix the indentation while moving it?
> 
> 
> For testing the actual change, `GET /forgot` (login/forgot_password.html) is the easiest one to test the new authforms work on. It looks pretty good, but the vertical alignment of the form is off-center, and there's a white rectangle (ostensibly a navbar) at the top of the page.

fixed the white bar and other issues. the centering seems to be a non-regression at the very least but tbh i have no idea how to fix it

**Review by TLSM — APPROVED** [review]
Significantly reduced line count and improved maintainability with removed duplicate code and reduced number of top-level templates. Also solves some style issues with alignment: the form is actually vertically centered in the viewport now!

Tested locally: the login, signup, and forgot password flows all work correctly. 2FA and reset password templates untested but look fine in the code.

**Comment by zorbathut** [comment]
:+1:

**Pull request merged**
